version: 2.1

setup: true

parameters:
  dev:
    type: string
    default: "no_change"

orbs:
  continuation: circleci/continuation@0.2.0

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - continuation/continue:
          configuration_path: .circleci/main.yml
workflows:
  setup:
    jobs:
      - setup
