version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.2.0

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Generate config
          command: |
            cat > main.yml \<<- EOF
            version: 2.1
            orbs:
              browser-tools: circleci/browser-tools@$BROWSER_TOOLS_VER
            jobs:
              job1:
                docker:
                  - image: circleci/ruby:2.6.2-node-browsers-legacy
                steps:
                  - run: echo dynamic configy
                  - browser-tools/install-browser-tools
                  - browser-tools/install-chromedriver
            workflows:
             workflow1:
              jobs:
               - job1
            EOF
      - continuation/continue:
          configuration_path: main.yml
workflows:
  setup:
    jobs:
      - setup
