version: 2.1
jobs:
  parameters:
    dev:
      type: string
      default: "no_change"
  build:
    docker:
      - image: cimg/ruby:2.7.4-browsers
    steps:
      - checkout
      - run: echo << parameters.dev >
      - run:
          name: hello
          command: echo "ohla"
