version: 2.1
jobs:
  build:
    parameters:
      dev:
        type: string
        default: "no_change"
    docker:
      - image: cimg/ruby:2.7.4-browsers
    steps:
      - checkout
      - run: echo << parameters.dev >
      - run:
          name: hello
          command: echo "ohla"
